# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: firsttracks

# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: fafauth-api

# "service" is the name of this project. This will also be added to your AWS resource names.
service: jamstack-auth-quickstart

provider:
  name: aws
  region: af-south-1
  runtime: python3.14

  domain:
    name: api.jamstack-auth.publicntp.net
    certificateArn: arn:aws:acm:af-south-1:293119271420:certificate/3d8d5f07-08e3-46c7-bae6-b9f794b8de8d
    createRoute53Record: false

  httpApi:
    # Disable the default 'execute-api' HTTP endpoint as we are using a custom domain
    disableDefaultEndpoint: true
    authorizers:
      kindeTokenAuthorizer:
        identitySource: $request.header.Authorization

        # Cache allow/deny determinations for a given bearer token for one hour
        resultTtlInSeconds: 3600

        issuerUrl: https://auth.jamstack-auth.publicntp.net
        audience:
          - https://api.jamstack-auth.publicntp.net

functions:

  ping:
    handler: handler.ping
    memorySize: 128
    events:
      - httpApi:
          path: /api/v001/ping
          method: get

  userGet:
    handler: handler.user_get
    memorySize: 128
    environment:
      # Required vars, even if MGMT mirrors them. :(
      KINDE_CLIENT_ID: ${param:KINDE_CLIENT_ID}
      KINDE_CLIENT_SECRET: ${param:KINDE_CLIENT_SECRET}

      # Kinde env variables to let us call the mgmt API -- secrets stored in Serverless Dashboard,
      #   meaning NOT-GitHub. :)
      MGMT_API_CLIENT_ID: ${param:MGMT_API_CLIENT_ID}
      MGMT_API_CLIENT_SECRET: ${param:MGMT_API_CLIENT_SECRET}

    events:
      - httpApi:
          path: /api/v001/user
          method: get
          authorizer:
            name: kindeTokenAuthorizer

custom:
  pythonRequirements:
    dockerizePip: true
